services:
    open_exchange_rates.manager.doctrine:
        class: Sirian\OpenExchangeRatesBundle\Manager\DoctrineORMExchangeRateManager
        arguments:
            - @?doctrine
            - Sirian\OpenExchangeRatesBundle\Entity\ExchangeRate

    open_exchange_rates.manager.doctrine_mongodb:
        class: Sirian\OpenExchangeRatesBundle\Manager\DoctrineODMExchangeRateManager
        arguments:
            - @doctrine_mongodb
            - Sirian\OpenExchangeRatesBundle\Document\ExchangeRate

    open_exchange_rates.manager: @open_exchange_rates.manager.doctrine
